Change approach to raw jinja

diff --git a/host_vars/localhost/bashrc.yml b/host_vars/localhost/bashrc.yml
--- a/host_vars/localhost/bashrc.yml
+++ b/host_vars/localhost/bashrc.yml
@@ -1,4 +1,5 @@
 my_bashrc: |
+  {% raw %}
   # ===============================
   # General environment variables
   # ===============================
@@ -7,7 +8,7 @@ my_bashrc: |
   export HISTSIZE=10000
   export HISTTIMEFORMAT="%F %T "
   export LESS='-X'
-  PROMPT_COMMAND="$$PROMPT_COMMAND; history -a; history -n"
+  PROMPT_COMMAND="$PROMPT_COMMAND; history -a; history -n"
 
   # =========================================
   # OpenShift Training environment variables
@@ -15,13 +16,13 @@ my_bashrc: |
 
   if [ -e /usr/local/etc/ocp4.config ]; then
     source /usr/local/etc/ocp4.config
-    M=$$RHT_OCP4_MASTER_API
-    WC=$$RHT_OCP4_WILDCARD_DOMAIN
-    NS=$$RHT_OCP4_NEXUS_SERVER
-    U=$$RHT_OCP4_DEV_USER
-    P=$$RHT_OCP4_DEV_PASSWORD
-    G=$$RHT_OCP4_GITHUB_USER
-    Q=$$RHT_OCP4_QUAY_USER
+    M=$RHT_OCP4_MASTER_API
+    WC=$RHT_OCP4_WILDCARD_DOMAIN
+    NS=$RHT_OCP4_NEXUS_SERVER
+    U=$RHT_OCP4_DEV_USER
+    P=$RHT_OCP4_DEV_PASSWORD
+    G=$RHT_OCP4_GITHUB_USER
+    Q=$RHT_OCP4_QUAY_USER
   else
     M=https://api.ocp4.example.com:6443
     WC=apps.ocp4.example.com
@@ -35,25 +36,25 @@ my_bashrc: |
   alias dl="oc login -u developer -p developer https://api.ocp4.example.com:6443"
   alias al="oc login -u admin -p redhatocp https://api.ocp4.example.com:6443"
   alias clustercheck="ssh lab@utility ./wait.sh"
-  alias events='oc get events --sort-by=".lastTimestamp" -n $$1'
-  alias podsw='oc get pods -o wide -n $$1'
+  alias events='oc get events --sort-by=".lastTimestamp" -n $1'
+  alias podsw='oc get pods -o wide -n $1'
   alias velero='oc -n openshift-adp exec deployment/velero -c velero -it -- ./velero'
 
   whohas() {
-    local role="$$1"
-    if [[ -z "$$role" ]]; then
+    local role="$1"
+    if [[ -z "$role" ]]; then
       echo "Usage: whohas <role>"
       return 1
     fi
-    oc get clusterrolebindings -o json | jq -r ".items[] | select(.roleRef.name == \"$$role\" and .subjects != null) | .subjects[] | \"$$(.kind) $$(.name)\"" || {
-      echo "Error: Could not find role $$role."
+    oc get clusterrolebindings -o json | jq -r ".items[] | select(.roleRef.name == \"$role\" and .subjects != null) | .subjects[] | \"\(.kind) \(.name)\"" || {
+      echo "Error: Could not find role $role."
       return 1
     }
   }
 
   whomembers() {
-    local group="$$1"
-    oc get group "$$group" -o json | jq -r '.users[]'
+    local group="$1"
+    oc get group "$group" -o json | jq -r '.users[]'
   }
 
   export GIT_PAGER=/usr/bin/cat
@@ -69,43 +70,43 @@ my_bashrc: |
   alias anv="ansible-navigator --version"
   alias anig="ansible-navigator inventory --graph"
   alias gc="git commit -m"
-  alias decomment='egrep -v "^[[:space:]]*((#|;|//).*)?$$" '
+  alias decomment='egrep -v "^[[:space:]]*((#|;|//).*)?$" '
   alias scp='echo -e "\nStop using scp\n\nSee https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know"'
   alias ve='python3 -m venv ./venv'
   alias va='source ./venv/bin/activate'
   alias showaliases="awk '/^alias/ {sub(/^alias[ \t]*/, \"\"); print}' /etc/bashrc"
 
   pastebin (){
-    local filename="$$1"
-    if [[ -z  "$$filename" ]]; then
+    local filename="$1"
+    if [[ -z  "$filename" ]]; then
         echo "Usage: pastebin /path/to/file"
         return 1
     fi
-    glab snippet create -pv public --filename $$filename --title $$filename
+    glab snippet create -pv public --filename $filename --title $filename
   }
 
   mcd (){
-    mkdir -pv "$$1"
-    cd "$$1" || return
+    mkdir -pv "$1"
+    cd "$1" || return
   }
 
   mnt (){
-    mount | awk '$$1 ~ /\/dev/ { print $$1,$$3; }' | column -t | sort
+    mount | awk '$1 ~ /\/dev/ { print $1,$3; }' | column -t | sort
   }
 
   gnb (){
-    git checkout -b "$$1"
-    git push -u origin "$$1"
+    git checkout -b "$1"
+    git push -u origin "$1"
   }
 
   my_ocp (){
-    echo 'M=$$RHT_OCP4_MASTER_API'
-    echo 'WC=$$RHT_OCP4_WILDCARD_DOMAIN'
-    echo 'NS=$$RHT_OCP4_NEXUS_SERVER'
-    echo 'U=$$RHT_OCP4_DEV_USER'
-    echo 'P=$$RHT_OCP4_DEV_PASSWORD'
-    echo 'G=$$RHT_OCP4_GITHUB_USER'
-    echo 'Q=$$RHT_OCP4_QUAY_USER'
+    echo 'M=$RHT_OCP4_MASTER_API'
+    echo 'WC=$RHT_OCP4_WILDCARD_DOMAIN'
+    echo 'NS=$RHT_OCP4_NEXUS_SERVER'
+    echo 'U=$RHT_OCP4_DEV_USER'
+    echo 'P=$RHT_OCP4_DEV_PASSWORD'
+    echo 'G=$RHT_OCP4_GITHUB_USER'
+    echo 'Q=$RHT_OCP4_QUAY_USER'
   }
 
   if command -v oc &> /dev/null; then
@@ -119,3 +120,4 @@ my_bashrc: |
   if command -v virtctl &> /dev/null; then
     source <(virtctl completion bash)
   fi
+  {% endraw %}
